apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260602-004613-50jrfxa8g4lw-service
spec:
  selector:
    app: enterprise-system-20260602-004613-50jrfxa8g4lw
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
